server:
  port: 18080
#spring:
##  activemq:
##    broker-url: tcp://127.0.0.1:61616
##    user: admin
##    password: admin
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.11:3306/db_data_base?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: MyNewPass4!

queue: springboot-queue

sharding.jdbc:
    datasource:
      names: db_data_base
      db_data_base:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.11:3306/db_data_base?characterEncoding=utf-8
        username: root
        password: MyNewPass4!
    config:
      sharding:
        tables:
          tb_order:
            actual-data-nodes: db_data_base.tb_order${0..1}
            table-strategy:
              standard:
                sharding-column: rid
                precise-algorithm-class-name: org.qhs.myproduct.config.MyPreciseShardingAlgorithm
